/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExercisesIndexRouteImport } from './routes/_authenticated/exercises.index'
import { Route as AuthenticatedExercisesNewRouteImport } from './routes/_authenticated/exercises.new'
import { Route as AuthenticatedExercisesIdRouteImport } from './routes/_authenticated/exercises.$id'
import { Route as AuthenticatedDatasetsIdRouteImport } from './routes/_authenticated/datasets.$id'
import { Route as ApiPublicCronSendDueReviewsRouteImport } from './routes/api/public/cron/send-due-reviews'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExercisesIndexRoute =
  AuthenticatedExercisesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExercisesRoute,
  } as any)
const AuthenticatedExercisesNewRoute =
  AuthenticatedExercisesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedExercisesRoute,
  } as any)
const AuthenticatedExercisesIdRoute =
  AuthenticatedExercisesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedExercisesRoute,
  } as any)
const AuthenticatedDatasetsIdRoute = AuthenticatedDatasetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDatasetsRoute,
} as any)
const ApiPublicCronSendDueReviewsRoute =
  ApiPublicCronSendDueReviewsRouteImport.update({
    id: '/api/public/cron/send-due-reviews',
    path: '/api/public/cron/send-due-reviews',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRouteWithChildren
  '/exercises': typeof AuthenticatedExercisesRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdRoute
  '/exercises/$id': typeof AuthenticatedExercisesIdRoute
  '/exercises/new': typeof AuthenticatedExercisesNewRoute
  '/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/api/public/cron/send-due-reviews': typeof ApiPublicCronSendDueReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdRoute
  '/exercises/$id': typeof AuthenticatedExercisesIdRoute
  '/exercises/new': typeof AuthenticatedExercisesNewRoute
  '/exercises': typeof AuthenticatedExercisesIndexRoute
  '/api/public/cron/send-due-reviews': typeof ApiPublicCronSendDueReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRouteWithChildren
  '/_authenticated/exercises': typeof AuthenticatedExercisesRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/datasets/$id': typeof AuthenticatedDatasetsIdRoute
  '/_authenticated/exercises/$id': typeof AuthenticatedExercisesIdRoute
  '/_authenticated/exercises/new': typeof AuthenticatedExercisesNewRoute
  '/_authenticated/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/api/public/cron/send-due-reviews': typeof ApiPublicCronSendDueReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/datasets'
    | '/exercises'
    | '/history'
    | '/settings'
    | '/datasets/$id'
    | '/exercises/$id'
    | '/exercises/new'
    | '/exercises/'
    | '/api/public/cron/send-due-reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/datasets'
    | '/history'
    | '/settings'
    | '/datasets/$id'
    | '/exercises/$id'
    | '/exercises/new'
    | '/exercises'
    | '/api/public/cron/send-due-reviews'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/datasets'
    | '/_authenticated/exercises'
    | '/_authenticated/history'
    | '/_authenticated/settings'
    | '/_authenticated/datasets/$id'
    | '/_authenticated/exercises/$id'
    | '/_authenticated/exercises/new'
    | '/_authenticated/exercises/'
    | '/api/public/cron/send-due-reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronSendDueReviewsRoute: typeof ApiPublicCronSendDueReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercises/': {
      id: '/_authenticated/exercises/'
      path: '/'
      fullPath: '/exercises/'
      preLoaderRoute: typeof AuthenticatedExercisesIndexRouteImport
      parentRoute: typeof AuthenticatedExercisesRoute
    }
    '/_authenticated/exercises/new': {
      id: '/_authenticated/exercises/new'
      path: '/new'
      fullPath: '/exercises/new'
      preLoaderRoute: typeof AuthenticatedExercisesNewRouteImport
      parentRoute: typeof AuthenticatedExercisesRoute
    }
    '/_authenticated/exercises/$id': {
      id: '/_authenticated/exercises/$id'
      path: '/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof AuthenticatedExercisesIdRouteImport
      parentRoute: typeof AuthenticatedExercisesRoute
    }
    '/_authenticated/datasets/$id': {
      id: '/_authenticated/datasets/$id'
      path: '/$id'
      fullPath: '/datasets/$id'
      preLoaderRoute: typeof AuthenticatedDatasetsIdRouteImport
      parentRoute: typeof AuthenticatedDatasetsRoute
    }
    '/api/public/cron/send-due-reviews': {
      id: '/api/public/cron/send-due-reviews'
      path: '/api/public/cron/send-due-reviews'
      fullPath: '/api/public/cron/send-due-reviews'
      preLoaderRoute: typeof ApiPublicCronSendDueReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDatasetsRouteChildren {
  AuthenticatedDatasetsIdRoute: typeof AuthenticatedDatasetsIdRoute
}

const AuthenticatedDatasetsRouteChildren: AuthenticatedDatasetsRouteChildren = {
  AuthenticatedDatasetsIdRoute: AuthenticatedDatasetsIdRoute,
}

const AuthenticatedDatasetsRouteWithChildren =
  AuthenticatedDatasetsRoute._addFileChildren(
    AuthenticatedDatasetsRouteChildren,
  )

interface AuthenticatedExercisesRouteChildren {
  AuthenticatedExercisesIdRoute: typeof AuthenticatedExercisesIdRoute
  AuthenticatedExercisesNewRoute: typeof AuthenticatedExercisesNewRoute
  AuthenticatedExercisesIndexRoute: typeof AuthenticatedExercisesIndexRoute
}

const AuthenticatedExercisesRouteChildren: AuthenticatedExercisesRouteChildren =
  {
    AuthenticatedExercisesIdRoute: AuthenticatedExercisesIdRoute,
    AuthenticatedExercisesNewRoute: AuthenticatedExercisesNewRoute,
    AuthenticatedExercisesIndexRoute: AuthenticatedExercisesIndexRoute,
  }

const AuthenticatedExercisesRouteWithChildren =
  AuthenticatedExercisesRoute._addFileChildren(
    AuthenticatedExercisesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRouteWithChildren
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRouteWithChildren,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronSendDueReviewsRoute: ApiPublicCronSendDueReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
